# Generated by Django 6.0.3 on 2026-03-23 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_compra', models.DateField()),
                ('cliente_nombre_snapshot', models.CharField(max_length=150)),
                ('cuit_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('total_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('resultado_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente')),
            ],
            options={
                'db_table': 'ventas_venta',
                'ordering': ['-fecha_compra', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto_nombre_snapshot', models.CharField(max_length=150)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('resultado_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta')),
            ],
            options={
                'db_table': 'ventas_venta_item',
                'ordering': ['id'],
            },
        ),
    ]
