# Generated by ChatGPT on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(blank=True, db_index=True, default='', max_length=8),
        ),
    ]
