# Generated by Django 6.0.3 on 2026-07-25 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pago_empresa'),
        ('ventas', '0004_proveedor_empresa_venta_empresa_alter_proveedor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ventas.venta'),
        ),
    ]
