# Generated by ChatGPT on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
